package user.exception.message

object UserErrorMessage {

    const val PASSWORD_MISMATCH = "Password Mismatch"

    const val USER_NOT_FOUND = "User Not Found"

    const val USER_ALREADY_EXISTS = "User Already Exists"
}