package auth.exception

object RefreshTokenNotFoundException {
}